# Generated by Django 2.2.2 on 2019-06-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0002_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nick_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
