# Generated by Django 2.2.2 on 2019-06-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0003_auto_20190611_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='instrument',
            field=models.ManyToManyField(help_text='Select instrument(s) for this player', to='jazz.Instrument'),
        ),
    ]
