# Generated by Django 2.2.2 on 2019-06-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0005_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['band_name', 'date'],
            },
        ),
    ]
