# Generated by Django 2.2.2 on 2019-06-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0007_auto_20190611_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='band_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jazz.Band'),
        ),
    ]
