# Generated by Django 2.2.2 on 2019-06-17 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0010_auto_20190616_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='lineup_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jazz.Lineup'),
        ),
    ]
