# Generated by Django 2.2.2 on 2019-06-17 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0011_band_lineup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='lineup_date',
        ),
        migrations.AddField(
            model_name='lineup',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jazz.Player'),
        ),
    ]
