# Generated by Django 2.2.2 on 2019-06-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0013_remove_lineup_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='piece',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
