# Generated by Django 2.2.2 on 2019-06-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0014_lineup_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jazz.Player'),
        ),
    ]
