# Generated by Django 2.2.2 on 2019-06-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0015_lineup_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineup',
            name='player',
        ),
        migrations.AddField(
            model_name='lineup',
            name='player',
            field=models.ManyToManyField(null=True, to='jazz.Player'),
        ),
    ]
