# Generated by Django 2.2.2 on 2019-06-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0016_auto_20190624_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='lineup',
            field=models.ManyToManyField(null=True, related_name='toLineups', to='jazz.Lineup'),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='player',
            field=models.ManyToManyField(null=True, related_name='toPlayer', to='jazz.Player'),
        ),
    ]
