# Generated by Django 2.2.2 on 2020-06-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0022_auto_20191022_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='instrument',
            field=models.CharField(help_text='Enter an instrument type', max_length=20),
        ),
    ]
