# Generated by Django 2.2.2 on 2020-06-07 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0023_auto_20200605_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='lineup',
        ),
        migrations.AddField(
            model_name='player',
            name='lineup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toLineups', to='jazz.Lineup'),
        ),
    ]
