# Generated by Django 2.2.2 on 2020-06-07 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0024_auto_20200607_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='instrument',
            field=models.ForeignKey(blank=True, help_text='Select instrument for this player', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jazz.Instrument'),
        ),
    ]
