# Generated by Django 2.2.2 on 2020-06-07 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0025_auto_20200607_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='lineup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toLineups', to='jazz.Lineup'),
        ),
    ]
