# Generated by Django 2.2.2 on 2020-06-07 12:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0026_auto_20200607_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineup',
            name='player',
        ),
        migrations.AddField(
            model_name='lineup',
            name='player',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='toPlayer', to='jazz.Player'),
            preserve_default=False,
        ),
    ]
