# Generated by Django 2.2.2 on 2020-06-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0028_remove_player_lineup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineup',
            name='piece',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='player',
        ),
    ]
