# Generated by Django 2.2.2 on 2020-06-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0029_auto_20200608_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineup',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='lineup',
            name='unique_lineup',
        ),
    ]
