# Generated by Django 2.2.2 on 2020-06-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0032_remove_lineup_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lineup',
        ),
    ]
