# Generated by Django 2.2.2 on 2020-07-01 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=100, unique=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('band_web', models.URLField(blank=True, verbose_name='Web Address')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['band_name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True)),
                ('event_web', models.URLField(blank=True, verbose_name='Web Address')),
                ('comments', models.CharField(blank=True, max_length=120, verbose_name='Comments')),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(help_text='Enter an instrument type', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=120, verbose_name='Venue Name')),
                ('venue_web', models.URLField(blank=True, verbose_name='Web Address')),
                ('comments', models.CharField(blank=True, max_length=120, verbose_name='Comments')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('nick_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Died')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('player_web', models.URLField(blank=True, verbose_name='Web Address')),
                ('instrument', models.ForeignKey(blank=True, help_text='Select instrument for this player', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jazz.Instrument')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('piece', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=120, verbose_name='Comments')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('band_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jazz.Band')),
                ('event', models.ForeignKey(blank=True, help_text='Select event type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jazz.Event')),
                ('player', models.ManyToManyField(to='jazz.Player')),
                ('venue', models.ForeignKey(blank=True, help_text='Select venue for this event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jazz.Venue')),
            ],
            options={
                'ordering': ['band_name', 'date'],
            },
        ),
        migrations.AddConstraint(
            model_name='lineup',
            constraint=models.UniqueConstraint(fields=('band_name', 'date'), name='unique_lineup'),
        ),
    ]
