# Generated by Django 2.2.2 on 2020-08-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jazz', '0003_auto_20200711_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_wikipedia',
            field=models.URLField(blank=True, verbose_name='Wikipedia Page'),
        ),
        migrations.AlterField(
            model_name='band',
            name='slug',
            field=models.SlugField(blank=True, max_length=125, unique=True),
        ),
    ]
